### ISSUE TITLE
Remote console IO error

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-hub/nerves_hub#106]
not 100% sure what is going on here..
```
** (EXIT from #PID<0.16173.6>) shell process exited with reason: an exception was raised:
    ** (FunctionClauseError) no function clause matching in RingLogger.Client.handle_info/2
        (ring_logger) lib/ring_logger/client.ex:155: RingLogger.Client.handle_info({:io_reply, #Reference<0.2340004039.277086209.158264>, "Supervisor.which_children(FarmbotExt.Bootstrap.Supervisor)"}, %RingLogger.Client.State{colors: %{debug: :cyan, enabled: true, error: :red, info: :normal, warn: :yellow}, format: ["\n", :time, " ", :metadata, "[", :level, "] ", :levelpad, :message, "\n"], index: 0, io: :stdio, level: :debug, metadata: [], module_levels: %{}})
        (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by fhunleth** [comment]
Did you call `RingLogger.attach` in the console?

The way that works is that RingLogger starts up a GenServer that receives log messages and prints them out to the local console. I assume that a log message got printed and then the IO server responded with an `:io_reply` to that GenServer's pid. I don't know enough about IO servers, but I'm pretty sure that somebody else was supposed to receive the `:io_reply`.

**Comment by ConnorRigby** [comment]
Yeah i called `RingLogger.attach()` then as soon as i called the next function that error happened. I too think that the `:io_reply` message was supposed to be received by another process. Not sure how it ended up at the RingLogger server

**Comment by jjcarstens** [comment]
This is really interesting. Technically, its working as expected because `RingLogger.attach` is starting a link to the running process (the remote IEx server) and messages are getting sent back and forth.

That means when `RingLogger` sends its `{:io_request, from, reply_as, request}`, it is going through the console channel because of the link. That channel is keeping state of `from` and `reply_as` so that it can properly respond to `get_line` requests that are asking for the next code to execute. But it looks like that is getting out of sync because `RingLogger.attach` adds another process that is _only_ putting characters and not expecting a response. i.e., this is what I got after causing RingLogger to print a message:
```elixir
{:io_request, #PID<0.451.0>, #Reference<0.1705606872.3671588868.1241>, {:put_chars, :latin1, "\e[22m\n13:08:04.230 [info]  tesT\n\e[0m"}}
```

This should be just a simple adjustment to only store the from/reply_as on `get_line` requests and _not_ `:put_chars`
