### ISSUE TITLE
Edit Deployments

### ISSUE THREAD

**Issue by paulstatezny** [nerves-hub/nerves_hub#40]
(Stub)

**Comment by stwf** [comment]
Am I right in thinking that the firmware_id on the deployment should not be editable? Its not a problem for the frontend, but it seems like it cause complications operationally?

If so then its just the name, and the conditions. The conditions which are broken out into version and tags. Is it that way so new things can be added into conditions? Otherwise it would be a simplification to just make version and tags separate fields....

**Comment by paulstatezny** [comment]
I agree with making condition and tags separate fields. Also with making firmware_id not editable.

**Comment by paulstatezny** [comment]
Also @stwf I'm not sure why `conditions` was made a JSONB field. It limits the constraints we can put on each field.

**Comment by stwf** [comment]
hmm, this probably needs more consideration. It may even look like conditions could be its own table with a relationship that a deployment has many conditions. Each of those could carry a JSON payload for maximum flexibility. So I actually think I shouldn't change anything schema related at this point? We can save that for after some discussion about the needs and features of the deployments. How does that sound?

**Comment by paulstatezny** [comment]
I'm fine with not changing things right now! Sounds good!

These are just my two cents, but I don't understand the viewpoint that the flexibility of JSONB fields is a positive thing for something like this. From my
Perspective, it (1) makes it less obvious what data the field could (and might) hold, and (2) limits the possibility of data integrity checks via the DB schema.

As someone doing maintenance on a codebase, I'd be frustrated if I had to spend a bunch of extra time just digging around to ensure I understand the range of possible data a JSONB field can hold. I really prefer just having the fields separated with the proper types because it's almost immediately clear.
