### ISSUE TITLE
Chicken and Egg setting public keys

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-hub/nerves_hub#47]
when adding `nerves_hub` as a dep to a new project having never created a nerves_hub account and signed in via the mix task, one cant make an account to create public keys because public keys don't exist yet. 

https://github.com/nerves-hub/nerves_hub/blob/master/lib/nerves_hub/certificate.ex#L2

**Comment by danielspofford** [comment]
With respect to CI:

I supply `NERVES_HUB_FW_PRIVATE_KEY` and `NERVES_HUB_FW_PUBLIC_KEY` which will satisfy https://github.com/nerves-hub/nerves_hub_cli/blob/master/lib/mix/nerves_hub/shell.ex#L53 but not https://github.com/nerves-hub/nerves_hub/blob/master/lib/nerves_hub/certificate.ex#L2

**Comment by fhunleth** [comment]
Some of our private keys are kept offline, so we solve this by not using the shortcut:

```elixir
config :nerves_hub,
  fwup_public_keys: [
    # devkey
    "bM/O9+ykZhCWx8uZVgx0sU3f0JJX7mqnAVU9VGeuHr4="
  ]
```
I added this to the `README.md`. I'm not sold that using the shortcut is a good idea except for development since it requires that you copy the signing private keys to the build machine even if they're not used. This configuration item is only for the fwup public keys to use when verifying downloaded firmware images. Signing is handled elsewhere.

[Closing since I don't think there's an action-item here or at least there's not one anymore]
