### ISSUE TITLE
Deploy a test server at nerves-hub.org

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub#69]

**Comment by mobileoverlord** [comment]
When talking about deployment it is important to talk through the infrastructure to see how we can maximize efficiency and safety in the development -> production lifecycle. Through this proposal I will be using the word `service` to generically refer to an OTP application release. NervesHub is currently expected to run two services in production. 

`nerves_hub` - publicly accessible web server that is responsible for handling all web and socket requests from users and devices.
`nerves_hub_ca` - private certificate authority service that is responsible for managing user / organization / and device certificate creation.

**Requirements**
* Services are portable.
The services should be packages for ease of deployment. In this case I would recommend that we have circle build a docker image for each tagged release of the service and upload it to dockerhub/nerveshub. The image will contain no secrets. The `entrypoint` for the image will be configured to execute a shell script which will fetch the secrets from a secure location and decorate the container environment on run. For NervesHub, we can use this script to call out to aws ssm parameter store for the secrets like DB usernames / passwords and such. By packaging the services using docker we can make it a lot easier for companies running private services to deploy them. 

* Service deployment is safe.
Things can go wrong form time to time so its important to have mechanisms in place that require releases to pass a series of health checks to go live. For this, I am recommending that we use a blue green deploy strategy for our running services. This strategy is very similar to how we handle firmware updates on the device. When performing a service upgrade, we would deploy to the inactive copy of the service. Once deployed, we execute a series of tests agains the new services. If they pass, we re route traffic to the upgraded service and deactivate the other.
 
* Service deployment is automated.
When deploying production releases, human intervention leaves the door open to lots of unforeseen error. Deploying the services into the infrastructure should be automated by scripts including running migrations. For `nerves-project` we trigger running the deployment routine on circle ci to version tagged releases. As an extra level of safety, we can add an approval phase that requires a team member have final sign off on cutting the service over to the new release. 

**NervesHub Deployments**
I recommend that we deploy into AWS especially since we are already going to be depending on S3 for firmware and certificate storage. With the services docker-ized, we can deploy using aws fargate so we don't need to get into managing our own ec2 infrastructure. It makes routing, scaling, and deploying a lot easier.

**NervesHub Workflow**
* CircleCI will execute a deploy task when encountering a tagged release
* The deploy task will
  * Build a docker image for the service and tag it
  * Upload the docker image to dockerhub
  * Initiate a blue green deploy
  * Wait for health checks to pass
  * Wait for circle ci approve step
  * Cut traffic over to new services
  * Deactivate old services

We use a lot of these practices at Le Tote so we can borrow things from there. These are based off a discussion I had regarding how we ship in production with @ tylerpearson

Please leave feedback on this proposal and if there is anything that you would recommend otherwise.

**Comment by mattlorey** [comment]
I think this all looks good, I've used Google Cloud with Kubernetes extensively so it will be good to see what it looks like with AWS.

**Comment by paulstatezny** [comment]
A lot of wisdom here. I like the concept for handling of secrets, and doing blue green deploys.

**Comment by mobileoverlord** [comment]
The new infrastructure is in place and live.
