### ISSUE TITLE
Better handling of  firmware metadata

### ISSUE THREAD

**Issue by jlmcgehee21** [nerves-hub/nerves_hub#91]
Currently, firmware `metadata` is being parsed for a few key fields, and then the entire `metadata` string is being stored in a `metadata` string field on a `firmware` record.  

The current issue, is that it is very common in the real world for the `metadata` field to be greater than the database imposed limit of 255 characters.

The proposed fix:
* A migration that removes the `metadata` string field, and adds the following relevant fields supplied by @fhunleth:
```
meta-product
meta-description
meta-version
meta-author
meta-platform
meta-architecture
meta-vcs-identifier
meta-misc
meta-uuid
```
* Refactor the `firmware_controller` and the `firmware` schema to handle these changes as well.

**Comment by fhunleth** [comment]
Regarding missing fields:
1. Once you have `fwup` 1.2.0 installed, the only guaranteed field is `meta-uuid`. It's possible for people to hack their .fw files to remove all of the other fields.
2. Nerves makes it very difficult to remove `meta-platform`, `meta-architecture`, and `meta-version` and keep things working. If those don't exist, I'd reject the .fw file since it probably won't work anyway.
3. All of the other fields can be set to empty strings. Empty strings aren't printed in `fwup`'s metadata dump. There's no concept of null if `fwup` so if a field isn't present, writing an empty string to the database would be consistent.

**Comment by danielspofford** [comment]
Do we want a dedicated column for `meta-creation-date` as well? That is read out of `metadata` [currently](https://github.com/nerves-hub/nerves_hub/blob/master/lib/nerves_hub/firmwares/firmware.ex#L56).

**Comment by danielspofford** [comment]
It already exists :), just asked because it wasn't listed above and other duplicates were.

**Comment by jlmcgehee21** [comment]
IMO, we should have columns for any metadata fields we store.

**Comment by fhunleth** [comment]
@danielspofford Thanks for bringing up `meta-creation-date`. I actually regret adding that field to `fwup` several years ago and I've been trying to get rid of it ever since. It's hard to get rid of fields, though. My vote would be to remove from Nerves Hub. I also left out `meta-fwup-version` above. Both fields seemed like a good idea at the time, but have the effect of making reproduceable .fw files difficult to make. By that, I mean that if you feed the same inputs to `fwup`, you'd think that you'd get an identical `.fw` file. Those fields mess that up. I don't think that I know of a project that has actually used them for something useful.

**Comment by danielspofford** [comment]
@fhunleth unless someone else has a strong opinion it sounds like we should wipeout `timestamp` from Nerves Hub. Which means drop the `timestamp` DB column and don't display it in the client.

**Comment by danielspofford** [comment]
@fhunleth I see this is assigned to @stwf, I hope I am not stepping on any toes, but I have some free time and could push something up today if that's ok. Would need GitHub permission to get sorted.

**Comment by fhunleth** [comment]
I'll get you permission shortly. I suspect that @stwf hasn't done anything on this, but we can double check on Slack.

**Comment by jlmcgehee21** [comment]
Closing issue, as it was addressed in https://github.com/nerves-hub/nerves_hub/pull/95
